theme: jekyll-theme-minimal
title: Burak Bayrakdar
description: Constantinopolitan in Batavia <img class="emoji" style="vertical-align:middle;" alt="nederland" height="20" width="20" src="/assets/img/nl.png">
logo: /assets/img/logo.png
favicon: /assets/img/favicon.ico
show_downloads: false

socialmedia:
  stackoverflow: 
    profile: https://stackoverflow.com/users/3641067/bur√¶quete?tab=profile
    flair: https://stackexchange.com/users/flair/4475914.png?theme=clean
  linkedin: https://www.linkedin.com/in/bvrakvs
  facebook: https://www.facebook.com/buraequete
  twitter: https://twitter.com/buraequete
  instagram: https://www.instagram.com/bvrakvs
  youtube: https://www.youtube.com/@bvrakvs
  spotify: https://open.spotify.com/user/w35zp8n0btspberptb0i06wiv
  steam: https://steamcommunity.com/id/bvrakvs
  projecteuler: https://projecteuler.net/profile/buraequete.png
  letterboxd: https://letterboxd.com/bvrakvs
  goodreads: http://goodreads.com/bvrakvs
